apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-config
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: cnoe://global-config
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: argocd
data:
  # These values can be overridden by idpbuilder command line arguments
  HOST: "cnoe.localtest.me"
  PORT: "8443"
  PROTOCOL: "https"
  
  # Derived values
  BASE_URL: "https://cnoe.localtest.me:8443"
  BASE_URL_NO_PORT: "https://cnoe.localtest.me"
  
  # Service-specific URLs
  BACKSTAGE_URL: "https://cnoe.localtest.me:8443/backstage"
  ARGOCD_URL: "https://cnoe.localtest.me:8443/argocd"
  GITEA_URL: "https://cnoe.localtest.me:8443/gitea"
  KEYCLOAK_URL: "https://cnoe.localtest.me:8443/keycloak"
  ARGO_WORKFLOWS_URL: "https://cnoe.localtest.me:8443/argo-workflows"
  
  # Gitea specific
  GITEA_HOST: "cnoe.localtest.me:8443"
  GITEA_HOST_NO_PORT: "cnoe.localtest.me"
  GITEA_CATALOG_URL: "https://cnoe.localtest.me/gitea/giteaAdmin/idpbuilder-localdev-backstage-templates-entities/raw/branch/main/catalog-info.yaml"
  
  # Keycloak specific
  KEYCLOAK_REALM: "cnoe"
  KEYCLOAK_METADATA_URL: "https://cnoe.localtest.me:8443/keycloak/realms/cnoe/.well-known/openid-configuration"
