apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    sso:
      insecureSkipVerify: true 
      issuer: ${ARGO_WORKFLOWS_KEYCLOAK_ISSUER}
      clientId:
        name: keycloak-oidc
        key: client-id
      clientSecret:
        name: keycloak-oidc
        key: secret-key
      redirectUrl: ${ARGO_WORKFLOWS_REDIRECT_URL}
      rbac:
        enabled: true
      scopes:
        - openid
        - profile
        - email
        - groups
    nodeEvents:
      enabled: false
