apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    sso:
      insecureSkipVerify: true 
      issuer: https://127.0.0.1:8080/keycloak/realms/cnoe
      clientId:
        name: keycloak-oidc
        key: client-id
      clientSecret:
        name: keycloak-oidc
        key: secret-key
      redirectUrl: https://127.0.0.1:8080/argo-workflows/oauth2/callback
      rbac:
        enabled: true
      scopes:
        - openid
        - profile
        - email
        - groups
    nodeEvents:
      enabled: false
