apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      containers:
        - name: argo-server
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
          env:
            - name: BASE_HREF
              value: "/argo-workflows/"
            - name: ARGO_WORKFLOWS_KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-config-values
                  key: KEYCLOAK_ISSUER
            - name: ARGO_WORKFLOWS_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-config-values
                  key: REDIRECT_URL
          args:
            - server
            - --configmap=workflow-controller-configmap
            - --auth-mode=client
            - --auth-mode=sso
            - "--secure=false"
            - "--loglevel"
            - "info"
            - "--log-format"
            - "text"
