apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: argo
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: keycloak-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_ID
    - secretKey: secret-key
      remoteRef:
        key: keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-config
  namespace: argo
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: argo-workflows-config
    template:
      engineVersion: v2
      data:
        ARGO_WORKFLOWS_KEYCLOAK_ISSUER: "{{.ARGO_WORKFLOWS_KEYCLOAK_ISSUER}}"
        ARGO_WORKFLOWS_REDIRECT_URL: "{{.ARGO_WORKFLOWS_REDIRECT_URL}}"
  data:
    - secretKey: ARGO_WORKFLOWS_KEYCLOAK_ISSUER
      remoteRef:
        key: argo-workflows-config-values
        property: KEYCLOAK_ISSUER
    - secretKey: ARGO_WORKFLOWS_REDIRECT_URL
      remoteRef:
        key: argo-workflows-config-values
        property: REDIRECT_URL
